apiVersion: observability.open-cluster-management.io/v1beta2
kind: MultiClusterObservability
metadata:
  name: observability
spec:
  # Optional, keep if you already standardize on it:
  imagePullPolicy: IfNotPresent

  # If you use sizing in your environment, keep your existing variable:
  instanceSize: 4xlarge

  advanced:
    retentionConfig:
      retentionResolution1h: 30d
      retentionResolution5m: 14d
      retentionResolutionRaw: 5d

  observabilityAddonSpec:
    enableMetrics: true
    interval: 60

  storageConfig:
    metricObjectStorage:
      name: thanos-object-storage
      key: thanos.yaml

      # Mount your S3 CA cert secret into the observability components:
      tlsSecretName: s3-ca-cert
      tlsSecretMountPath: /etc/s3/certs
