apiVersion: observability.open-cluster-management.io/v1beta2
kind: MultiClusterObservability
metadata:
  name: observability
spec:
  imagePullPolicy: IfNotPresent

  # Keep this conservative for portability across hubs.
  # Increase per hub capacity only after validating PVC binding + CPU headroom.
  instanceSize: large

  advanced:
    retentionConfig:
      retentionResolution1h: 30d
      retentionResolution5m: 14d
      retentionResolutionRaw: 5d

    # Short-term stability / capacity-safe default:
    # Prevents "one receive pod Pending" -> "ForwardFailed" scenarios on smaller hubs.
    receive:
      replicas: 5

  observabilityAddonSpec:
    enableMetrics: true
    interval: 60

  storageConfig:
    metricObjectStorage:
      name: thanos-object-storage
      key: thanos.yaml

      # S3/TLS (CA bundle) secret for the object storage endpoint
      tlsSecretName: s3-ca-cert
      tlsSecretMountPath: /etc/s3/certs

