apiVersion: v1
kind: Secret
metadata:
  name: thanos-object-storage
  namespace: open-cluster-management-observability
type: Opaque
stringData:
  thanos.yaml: |
    type: s3
    config:
      bucket: <BUCKET_NAME>
      endpoint: <S3_ENDPOINT_NO_PROTOCOL>   # example: minio.apps.example.com:443
      insecure: false
      access_key: <ACCESS_KEY>
      secret_key: <SECRET_KEY>

      # Trust your internal CA (mounted via tlsSecretMountPath below)
      http_config:
        tls_config:
          ca_file: /etc/s3/certs/ca.crt
